// Fake Amazon product list
export const fakeProducts = [
  {
    id: 1,
    title: "Echo Dot (5th Gen)",
    price: "$49.99",
    icon: "MicIcon",
  },
  {
    id: 2,
    title: "Fire TV Stick 4K",
    price: "$39.99",
    icon: "TvIcon",
  },
  {
    id: 3,
    title: "Kindle Paperwhite",
    price: "$129.99",
    icon: "BookIcon",
  },
  {
    id: 4,
    title: "Amazon Basics AA Batteries (20-Pack)",
    price: "$10.99",
    icon: "BatteryIcon",
  },
  {
    id: 5,
    title: "Instant Pot Duo 7-in-1",
    price: "$89.99",
    icon: "HomeIcon",
  },
  {
    id: 6,
    title: "Apple AirPods Pro (2nd Gen)",
    price: "$249.99",
    icon: "HeadphonesIcon",
  },
  {
    id: 7,
    title: "Samsung 32-Inch 4K Monitor",
    price: "$299.99",
    icon: "MonitorIcon",
  },
  // Additional products
  {
    id: 8,
    title: "Logitech Wireless Mouse",
    price: "$24.99",
    icon: "MonitorIcon",
  },
  {
    id: 9,
    title: "Philips Hue Smart Bulb",
    price: "$34.99",
    icon: "HomeIcon",
  },
  {
    id: 10,
    title: "JBL Bluetooth Speaker",
    price: "$59.99",
    icon: "HeadphonesIcon",
  },
  {
    id: 11,
    title: "Anker Power Bank 20000mAh",
    price: "$39.99",
    icon: "BatteryIcon",
  },
  {
    id: 12,
    title: "HP Envy 13 Laptop",
    price: "$799.99",
    icon: "MonitorIcon",
  },
  {
    id: 13,
    title: "Instant Read Meat Thermometer",
    price: "$15.99",
    icon: "HomeIcon",
  },
  {
    id: 14,
    title: "Sony WH-1000XM4 Headphones",
    price: "$348.00",
    icon: "HeadphonesIcon",
  },
  {
    id: 15,
    title: "Tile Mate Bluetooth Tracker",
    price: "$19.99",
    icon: "BatteryIcon",
  },
  {
    id: 16,
    title: "Apple iPad (9th Gen)",
    price: "$329.99",
    icon: "MonitorIcon",
  },
  {
    id: 17,
    title: "Amazon Fire HD 8 Tablet",
    price: "$89.99",
    icon: "MonitorIcon",
  },
  {
    id: 18,
    title: "Google Nest Thermostat",
    price: "$129.99",
    icon: "HomeIcon",
  },
  {
    id: 19,
    title: "Samsung Galaxy Buds Pro",
    price: "$199.99",
    icon: "HeadphonesIcon",
  },
  {
    id: 20,
    title: "Brother Compact Laser Printer",
    price: "$149.99",
    icon: "MonitorIcon",
  },
  {
    id: 21,
    title: "Ring Video Doorbell 4",
    price: "$199.99",
    icon: "HomeIcon",
  },
  {
    id: 22,
    title: "Kindle Oasis E-reader",
    price: "$249.99",
    icon: "BookIcon",
  },
  {
    id: 23,
    title: "Bose SoundLink Revolve+ Speaker",
    price: "$299.00",
    icon: "HeadphonesIcon",
  },
  {
    id: 24,
    title: "TP-Link WiFi 6 Router",
    price: "$89.99",
    icon: "MonitorIcon",
  },
  {
    id: 25,
    title: "Garmin Forerunner 245 Smartwatch",
    price: "$249.99",
    icon: "MonitorIcon",
  },
  {
    id: 26,
    title: "Hamilton Beach Electric Kettle",
    price: "$39.99",
    icon: "HomeIcon",
  },
  {
    id: 27,
    title: "Roku Streaming Stick+",
    price: "$49.99",
    icon: "TvIcon",
  },
  {
    id: 28,
    title: "Canon EOS Rebel T7 Camera",
    price: "$479.99",
    icon: "MonitorIcon",
  },
  {
    id: 29,
    title: "Oral-B Genius X Electric Toothbrush",
    price: "$179.99",
    icon: "HomeIcon",
  },
  {
    id: 30,
    title: "SanDisk 1TB Portable SSD",
    price: "$119.99",
    icon: "BatteryIcon",
  },
  {
    id: 31,
    title: "Tile Pro Bluetooth Tracker",
    price: "$34.99",
    icon: "BatteryIcon",
  },
  {
    id: 32,
    title: "Apple MacBook Air (M2)",
    price: "$1,099.99",
    icon: "MonitorIcon",
  },
  {
    id: 33,
    title: "Chefman Air Fryer",
    price: "$99.99",
    icon: "HomeIcon",
  },
  {
    id: 34,
    title: "Amazon Echo Show 8",
    price: "$129.99",
    icon: "MicIcon",
  },
  {
    id: 35,
    title: "HP OfficeJet All-in-One Printer",
    price: "$179.99",
    icon: "MonitorIcon",
  },
  {
    id: 36,
    title: "Samsung T7 Touch Portable SSD",
    price: "$139.99",
    icon: "BatteryIcon",
  },
  {
    id: 37,
    title: "Nest Protect Smoke Alarm",
    price: "$119.99",
    icon: "HomeIcon",
  },
  {
    id: 38,
    title: "Sony SRS-XB43 Bluetooth Speaker",
    price: "$178.00",
    icon: "HeadphonesIcon",
  },
  {
    id: 39,
    title: "Wyze Cam v3 Security Camera",
    price: "$35.98",
    icon: "MonitorIcon",
  },
  {
    id: 40,
    title: "Amazon Basics 6-Outlet Surge Protector",
    price: "$12.99",
    icon: "BatteryIcon",
  },
];
